import {defineConfig} from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import {viteExternalsPlugin} from "vite-plugin-externals";

export default defineConfig({
    define: {
        'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'production'),
    },
    plugins: [
        react(),
        viteExternalsPlugin({
            react: 'React',
            axios: 'axios',
            sonner: 'sonner',
            'lucide-react': 'LucideReact',
            'react-dom': 'ReactDOM',
            '@/components/ui/avatar': 'UIComponents',
            '@/components/ui/badge': 'UIComponents',
            '@/components/ui/breadcrumb': 'UIComponents',
            '@/components/ui/button': 'UIComponents',
            '@/components/ui/calendar': 'UIComponents',
            '@/components/ui/card': 'UIComponents',
            '@/components/ui/checkbox': 'UIComponents',
            '@/components/ui/collapsible': 'UIComponents',
            '@/components/ui/command': 'UIComponents',
            '@/components/ui/context-menu': 'UIComponents',
            '@/components/ui/dialog': 'UIComponents',
            '@/components/ui/dialog-stack': 'UIComponents',
            '@/components/ui/dropdown-menu': 'UIComponents',
            '@/components/ui/input': 'UIComponents',
            '@/components/ui/label': 'UIComponents',
            '@/components/ui/menubar': 'UIComponents',
            '@/components/ui/pagination': 'UIComponents',
            '@/components/ui/popover': 'UIComponents',
            '@/components/ui/select': 'UIComponents',
            '@/components/ui/separator': 'UIComponents',
            '@/components/ui/sheet': 'UIComponents',
            '@/components/ui/sidebar': 'UIComponents',
            '@/components/ui/skeleton': 'UIComponents',
            '@/components/ui/slider': 'UIComponents',
            '@/components/ui/sonner': 'UIComponents',
            '@/components/ui/switch': 'UIComponents',
            '@/components/ui/table': 'UIComponents',
            '@/components/ui/textarea': 'UIComponents',
            '@/components/ui/tooltip': 'UIComponents',
        }),
    ],
    build: {
        outDir: path.resolve(import.meta.dirname, ''),
        // outDir: path.resolve(import.meta.dirname, 'dist/assets'),
        emptyOutDir: false,
        lib: {
            // Library entrance point
            entry: path.resolve(import.meta.dirname, 'ComponentB'),
            name: 'ComponentB',
            formats: ['es'],
            fileName: (format) => `ComponentB.${format}.js`,
        },
        rollupOptions: {
            external: [
                'tailwindcss',
                '@/components/ui/avatar',
                '@/components/ui/badge',
                '@/components/ui/breadcrumb',
                '@/components/ui/button',
                '@/components/ui/calendar',
                '@/components/ui/card',
                '@/components/ui/checkbox',
                '@/components/ui/collapsible',
                '@/components/ui/command',
                '@/components/ui/context-menu',
                '@/components/ui/dialog',
                '@/components/ui/dialog-stack',
                '@/components/ui/dropdown-menu',
                '@/components/ui/input',
                '@/components/ui/label',
                '@/components/ui/menubar',
                '@/components/ui/pagination',
                '@/components/ui/popover',
                '@/components/ui/select',
                '@/components/ui/separator',
                '@/components/ui/sheet',
                '@/components/ui/sidebar',
                '@/components/ui/skeleton',
                '@/components/ui/slider',
                '@/components/ui/sonner',
                '@/components/ui/switch',
                '@/components/ui/table',
                '@/components/ui/textarea',
                '@/components/ui/tooltip',
            ],
        },
    },
    resolve: {
        alias: {
            '@': path.resolve(import.meta.dirname, '../../src/assets/js'),
        },
    },
});
