import {defineConfig} from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import {viteExternalsPlugin} from "vite-plugin-externals";

export default defineConfig({
    define: {
        'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'production'),
    },
    plugins: [
        react(),
        viteExternalsPlugin({
            react: 'React',
            'react-dom': 'ReactDOM',
            '@/components/ui/avatar.tsx': 'UIComponents',
            '@/components/ui/badge.tsx': 'UIComponents',
            '@/components/ui/breadcrumb.tsx': 'UIComponents',
            '@/components/ui/button.tsx': 'UIComponents',
            '@/components/ui/calendar.tsx': 'UIComponents',
            '@/components/ui/card.tsx': 'UIComponents',
            '@/components/ui/checkbox.tsx': 'UIComponents',
            '@/components/ui/collapsible.tsx': 'UIComponents',
            '@/components/ui/command.tsx': 'UIComponents',
            '@/components/ui/context-menu.tsx': 'UIComponents',
            '@/components/ui/dialog.tsx': 'UIComponents',
            '@/components/ui/dialog-stack.tsx': 'UIComponents',
            '@/components/ui/dropdown-menu.tsx': 'UIComponents',
            '@/components/ui/input.tsx': 'UIComponents',
            '@/components/ui/label.tsx': 'UIComponents',
            '@/components/ui/menubar.tsx': 'UIComponents',
            '@/components/ui/pagination.tsx': 'UIComponents',
            '@/components/ui/popover.tsx': 'UIComponents',
            '@/components/ui/select.tsx': 'UIComponents',
            '@/components/ui/separator.tsx': 'UIComponents',
            '@/components/ui/sheet.tsx': 'UIComponents',
            '@/components/ui/sidebar.tsx': 'UIComponents',
            '@/components/ui/skeleton.tsx': 'UIComponents',
            '@/components/ui/slider.tsx': 'UIComponents',
            '@/components/ui/sonner.tsx': 'UIComponents',
            '@/components/ui/switch.tsx': 'UIComponents',
            '@/components/ui/table.tsx': 'UIComponents',
            '@/components/ui/textarea.tsx': 'UIComponents',
            '@/components/ui/tooltip.tsx': 'UIComponents',
        }),
    ],
    build: {
        outDir: path.resolve(import.meta.dirname, ''),
        // outDir: path.resolve(import.meta.dirname, 'dist/assets'),
        emptyOutDir: false,
        lib: {
            // Library entrance point
            entry: path.resolve(import.meta.dirname, 'ComponentB.tsx'),
            name: 'ComponentB',
            formats: ['es'],
            fileName: (format) => `ComponentB.${format}.js`,
        },
        rollupOptions: {
            external: [
                'tailwindcss',
                '@/components/ui/avatar.tsx',
                '@/components/ui/badge.tsx',
                '@/components/ui/breadcrumb.tsx',
                '@/components/ui/button.tsx',
                '@/components/ui/calendar.tsx',
                '@/components/ui/card.tsx',
                '@/components/ui/checkbox.tsx',
                '@/components/ui/collapsible.tsx',
                '@/components/ui/command.tsx',
                '@/components/ui/context-menu.tsx',
                '@/components/ui/dialog.tsx',
                '@/components/ui/dialog-stack.tsx',
                '@/components/ui/dropdown-menu.tsx',
                '@/components/ui/input.tsx',
                '@/components/ui/label.tsx',
                '@/components/ui/menubar.tsx',
                '@/components/ui/pagination.tsx',
                '@/components/ui/popover.tsx',
                '@/components/ui/select.tsx',
                '@/components/ui/separator.tsx',
                '@/components/ui/sheet.tsx',
                '@/components/ui/sidebar.tsx',
                '@/components/ui/skeleton.tsx',
                '@/components/ui/slider.tsx',
                '@/components/ui/sonner.tsx',
                '@/components/ui/switch.tsx',
                '@/components/ui/table.tsx',
                '@/components/ui/textarea.tsx',
                '@/components/ui/tooltip.tsx',
            ],
        },
    },
    resolve: {
        alias: {
            '@': path.resolve(import.meta.dirname, '../../src/assets/js'),
        },
    },
});
